name: "AyuGram Webtop"
version: "1.1.1"
slug: "ayugram_webtop"
description: "Run AyuGram (Telegram Desktop) in a Docker container and access it via the browser from anywhere."
url: "https://github.com/jigurdas/ha-ayugram-addon/tree/main/ayugram"
startup: application
arch:
  - amd64
  - aarch64
init: false
ingress: true
ingress_port: 6901
panel_admin: true
panel_icon: mdi:telegram
panel_title: AyuGram
host_network: false
apparmor: false
services: []
ports:
  "6901/tcp": 6901
ports_description:
  "6901/tcp": "Web GUI (HTTPS)"
map: []
schema: {}
image: "ghcr.io/jigurdas/ha-ayugram-addon-{arch}"
